update arc.js 56
daostack/alchemy pull request #2140
Opened 2020-09-17 11:18 UTC by roienatan

2020-09-20 13:15 UTC, roienatan commented
@dkent600 The issue with the proposal count (https://github.com/daostack/alchemy/issues/2049) happens because `pluginState` in not updated. I'm not sure it's related to the polling.

2020-09-20 13:45 UTC, dkent600 commented
> @dkent600 The issue with the proposal count (#2049) happens because `pluginState` in not updated. I'm not sure it's related to the polling.

If Alchemy is supplying subscribe:true when it requests the proposalState, then the state should be updated by polling.

2020-09-20 14:01 UTC, roienatan commented
> > @dkent600 The issue with the proposal count (#2049) happens because `pluginState` in not updated. I'm not sure it's related to the polling.
> 
> If Alchemy is supplying subscribe:true when it requests the proposalState, then the state should be updated by polling.

I say this because I tried to replace **all** `subscribe: true` to `polling: true` and still the counters didn't update. That's why I might think that there is a problem in Alchemy code itself (which for now I didn't find) and that's why I asked you if you recall that those counters were properly working before.

2020-09-21 05:58 UTC, orenyodfat requested changes
The following lines need to be updated : 
https://github.com/daostack/alchemy/blob/update-arcjs-56/src/components/Account/AccountProfilePage.tsx#L358

https://github.com/daostack/alchemy/blob/update-arcjs-56/src/components/Plugin/ContributionRewardExtRewarders/Competition/List.tsx#L140

2020-09-21 06:04 UTC, orenyodfat commented
> > > @dkent600 The issue with the proposal count (#2049) happens because `pluginState` in not updated. I'm not sure it's related to the polling.
> > 
> > 
> > If Alchemy is supplying subscribe:true when it requests the proposalState, then the state should be updated by polling.
> 
> I say this because I tried to replace **all** `subscribe: true` to `polling: true` and still the counters didn't update. That's why I might think that there is a problem in Alchemy code itself (which for now I didn't find) and that's why I asked you if you recall that those counters were properly working before.

how about updating this as well ? https://github.com/daostack/alchemy/blob/update-arcjs-56/src/components/Dao/ProposalPluginCard.tsx#L103 ?

2020-09-22 13:06 UTC, orenyodfat commented on src/components/Plugin/ContributionRewardExtRewarders/Competition/utils.ts
> +//     CompetitionSuggestion.search(getArc(), {}, { polling: true, fetchAllData: true }),
lets remove these comments lines ?

2020-09-23 03:14 UTC, orenyodfat requested changes
lets set the polling time to 30 seconds and have it on a single global var

2020-09-23 08:38 UTC, merged