Avoid crashing Alchemy when there is no network or The Graph servers are overloaded
daostack/alchemy pull request #2230
Opened 2020-11-01 09:46 UTC by roienatan

2020-11-01 11:17 UTC, orenyodfat requested changes
it does not seems to continue polling after the network error

2020-11-01 12:04 UTC, roienatan commented
> it does not seems to continue polling after the network error

Looks like React Apollo Client does not resume polling after a network error, see this:
https://github.com/apollographql/apollo-client/issues/1099
I need to investigate and see if there is an option to resume the polling. The fix might be in arc.js if so.

2020-11-02 07:04 UTC, orenyodfat commented on src/arc.ts
> +        if (count === 10) {
this lines can be changed to : 
`return (count !== 10);`

2020-11-02 07:05 UTC, orenyodfat commented on src/arc.ts
> +        return Math.floor(Math.random() * (30000 - 5000 + 1) + 5000);
lets add a comment here : 
" this will give a random delay between retries between the range of 5 to 30 seconds"

2020-11-02 08:04 UTC, orenyodfat approved these changes

2020-11-02 08:12 UTC, merged